// Code generated by goyacc -l -o parser.go kaleido_grammar.y. DO NOT EDIT.
package main

import __yyfmt__ "fmt"

import "log"
import "unicode/utf8"
import "alea.net/xp/llvm/kaleidoscope/ast"
import "alea.net/xp/llvm/kaleidoscope/lexer"

type yySymType struct {
	yys      int
	token    lexer.KaleidoTokenContext
	proto    ast.PrototypeAST
	function ast.FunctionAST
	expr     ast.ExprAST
	argList  ast.ArgList
	exprList ast.ExprList
}

const DEF = 57346
const EXTERN = 57347
const NUMBER = 57348
const IDENTIFIER = 57349

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"DEF",
	"EXTERN",
	"NUMBER",
	"'<'",
	"'+'",
	"'-'",
	"'*'",
	"IDENTIFIER",
	"'('",
	"';'",
	"')'",
	"','",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

const EOF = 0

type Scanner struct {
	lexer.KaleidoLexer
}

func (s *Scanner) Lex(lval *yySymType) int {
	tokenContext := s.NextToken()
	lval.token = *tokenContext
	switch tokenContext.Token {
	case lexer.KTokenEOF:
		return EOF
	case lexer.KTokenDef:
		return DEF
	case lexer.KTokenExtern:
		return EXTERN
	case lexer.KTokenIdentifier:
		return IDENTIFIER
	case lexer.KTokenNumber:
		return NUMBER
	default:
		val, _ := utf8.DecodeRuneInString(tokenContext.Value)
		return int(val)
	}
}

func (s *Scanner) Error(e string) {
	panic(e)
}

func Parse(buffer string) {
	scanner := Scanner{KaleidoLexer: lexer.NewKaleidoLexer(buffer)}
	yyParse(&scanner)
}

var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 52

var yyAct = [...]int{
	8, 18, 16, 17, 19, 39, 37, 38, 32, 36,
	10, 24, 2, 21, 22, 9, 12, 25, 26, 27,
	28, 31, 6, 7, 10, 16, 17, 19, 23, 9,
	12, 18, 16, 17, 19, 20, 41, 35, 40, 14,
	19, 13, 34, 33, 30, 29, 11, 5, 4, 15,
	3, 1,
}

var yyPact = [...]int{
	-1, 18, -1000, -1000, -1000, -1000, 28, 28, 24, 23,
	-1000, -1000, 4, 4, 16, -2, 4, 4, 4, 4,
	4, -6, 24, 26, -1000, 30, 30, 17, -1000, -5,
	-9, 24, -1000, -7, -10, -1000, -1000, 4, -1000, 25,
	24, -1000,
}

var yyPgo = [...]int{
	0, 51, 50, 48, 47, 41, 0, 46, 45, 44,
	43, 42,
}

var yyR1 = [...]int{
	0, 1, 1, 1, 1, 1, 2, 3, 4, 6,
	6, 6, 6, 6, 6, 6, 6, 7, 8, 8,
	9, 9, 5, 10, 10, 11, 11,
}

var yyR2 = [...]int{
	0, 2, 2, 2, 1, 0, 3, 3, 1, 1,
	1, 1, 3, 3, 3, 3, 3, 4, 1, 0,
	3, 1, 4, 1, 0, 3, 1,
}

var yyChk = [...]int{
	-1000, -1, 13, -2, -3, -4, 4, 5, -6, 11,
	6, -7, 12, -5, 11, -5, 8, 9, 7, 10,
	12, -6, -6, 12, 13, -6, -6, -6, -6, -8,
	-9, -6, 14, -10, -11, 11, 14, 15, 14, 15,
	-6, 11,
}

var yyDef = [...]int{
	5, -2, 4, 1, 2, 3, 0, 0, 8, 9,
	10, 11, 0, 0, 0, 0, 0, 0, 0, 0,
	19, 0, 6, 24, 7, 13, 14, 15, 16, 0,
	18, 21, 12, 0, 23, 26, 17, 0, 22, 0,
	20, 25,
}

var yyTok1 = [...]int{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	12, 14, 10, 8, 15, 9, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 13,
	7,
}

var yyTok2 = [...]int{
	2, 3, 4, 5, 6, 11,
}

var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 6:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			log.Println("Parsed rule: Def")
		}
	case 7:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			log.Println("Parsed rule: Ext")
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			log.Println("Parsed rule: TopLevelExpr")
		}
	case 17:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			log.Println("Parsed rule: FuncExpr")
		}
	case 22:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			log.Println("Parsed rule: Prototype")
		}
	}
	goto yystack /* stack new state and value */
}
