name: Build Kaleidoscope

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:

    - name: Install LLVM package repository public key
      run: wget --no-check-certificate -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -

    - name: Add LLVM 12 binary package repository 
      run: sudo add-apt-repository 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-12 main'

    - name: Update Ubuntu package list
      run: sudo apt-get update
      
    - name: Install LLVM 12
      run: sudo apt-get install llvm-12 llvm-12-dev

    - name: Prepare environment variables
      run: |
        echo "CGO_CPPFLAGS=`/usr/bin/llvm-config-12 --cppflags`" >> $GITHUB_ENV
        echo "CGO_CXXFLAGS=-std=c++14" >> $GITHUB_ENV
        echo "CGO_LDFLAGS=`echo $(/usr/bin/llvm-config-12 --ldflags --libs --system-libs all)`" >> $GITHUB_ENV

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - uses: actions/checkout@v2

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
